name: Coverage CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gcc9-codecov:
    runs-on: ubuntu-latest
    name: GNU GCC 9 and run codecov
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install GCC 9 and GCOV
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-9
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
        sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 90
    - name: Build mockturtle
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-9 -DMOCKTURTLE_TEST=ON -DENABLE_COVERAGE=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
    - name: Debug Coverage Data
      run: |
        sudo apt-get install lcov
        lcov -t "debug" -o debug.info -c -d .
        lcov -l debug.info
    - name: Run lcov
      run: |
        sudo apt-get install lcov
        find . -name "*.gcda" -exec rm -f {} +
        find . -name "*.gcno" -exec rm -f {} +
        lcov -t "result" -o lcov.info -c -d .
        lcov --rc geninfo_unexecuted_blocks=1 --ignore-errors mismatch -e lcov.info "*mockturtle/include*" -o lcov_filtered.info
        lcov -l lcov_filtered.info
    - name: CodeCov
      uses: codecov/codecov-action@v2
      with:
        files: ./lcov_filtered.info
