name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: g++-9
            compiler: g++-9
            cxx: /usr/bin/g++-9
            flags: ""
            os: ubuntu-latest

          - name: g++-10
            compiler: g++-10
            cxx: /usr/bin/g++-10
            flags: ""
            os: ubuntu-latest

          - name: g++-10-cpp20
            compiler: g++-10
            cxx: /usr/bin/g++-10
            flags: "-DMOCKTURTLE_CXX_STANDARD=20"
            os: ubuntu-latest

          - name: g++-12
            compiler: g++-12
            cxx: /usr/bin/g++-12
            flags: ""
            os: ubuntu-latest

          - name: clang++-11
            compiler: clang-11
            cxx: /usr/bin/clang++-11
            flags: ""
            os: ubuntu-22.04

          - name: clang++-13
            compiler: clang-13
            cxx: /usr/bin/clang++-13
            flags: ""
            os: ubuntu-22.04

    runs-on: ${{ matrix.os }}
    name: Build with ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install Compiler
        run: |
          sudo apt-get update
          if [[ "${{ matrix.compiler }}" == clang-* ]]; then
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get update
          fi
          sudo apt-get install -y ${{ matrix.compiler }}
          export CXX=${{ matrix.cxx }}
          export CC=${{ matrix.cxx/++/ }}
          which $CXX || { echo "$CXX not found"; exit 1; }
          $CXX --version

      - name: Build mockturtle
        run: |
          mkdir build
          cd build
          cmake ${{ matrix.flags }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -DMOCKTURTLE_TEST=ON ..
          make run_tests

      - name: Run tests
        run: |
          cd build
          ./test/run_tests "~[quality]"

  compile-all:
    runs-on: ubuntu-latest
    name: Compile all examples and experiments (GCC 9)

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install GCC 9
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-9
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
          sudo update-alternatives --set g++ /usr/bin/g++-9
          export CXX=/usr/bin/g++-9
          g++ --version

      - name: Build all targets
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=g++-9 -DMOCKTURTLE_EXAMPLES=ON -DMOCKTURTLE_EXPERIMENTS=ON -DMOCKTURTLE_TEST=ON ..
          make
