name: Linux CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-gcc9:
    runs-on: ubuntu-latest
    name: GNU GCC 9
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install GCC 9
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-9
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
        sudo update-alternatives --set g++ /usr/bin/g++-9
        export CXX=/usr/bin/g++-9  # Explicitly set the compiler
        g++ --version  # Verify installation
    - name: Debug Compiler Installation
      run: |
        which g++
        g++ --version
        echo $CXX  # Verify CXX environment variable
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-9 -DMOCKTURTLE_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  build-gcc10:
    runs-on: ubuntu-latest
    name: GNU GCC 10
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install GCC 10
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        sudo update-alternatives --set g++ /usr/bin/g++-10
        g++ --version # Verify installation
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-10 -DMOCKTURTLE_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  build-gcc10-cpp20:
    runs-on: ubuntu-latest
    name: GNU GCC 10 (c++20)

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DMOCKTURTLE_CXX_STANDARD=20 -DCMAKE_CXX_COMPILER=g++-10 -DMOCKTURTLE_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  build-gcc12:
    runs-on: ubuntu-latest
    name: GNU GCC 12
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-12 -DMOCKTURTLE_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  build-clang11:
    runs-on: ubuntu-latest
    name: Clang 11
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=clang++-11 -DMOCKTURTLE_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  build-clang13:
    runs-on: ubuntu-latest
    name: Clang 13
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=clang++-13 -DMOCKTURTLE_TEST=ON ..
        make run_tests
    - name: Run tests
      run: |
        cd build
        ./test/run_tests "~[quality]"
  compile-gcc9:
    runs-on: ubuntu-latest
    name: Compile everything (GCC 9)
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install GCC 9
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-9
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
        sudo update-alternatives --set g++ /usr/bin/g++-9
        export CXX=/usr/bin/g++-9  # Explicitly set the compiler
        g++ --version  # Verify installation

        if ! which g++; then
          echo "Error: g++ is not installed or not in PATH." >&2
          exit 1
        fi
        if ! g++ --version | grep "9."; then
          echo "Error: g++ version is not GCC 9." >&2
          exit 1
        fi

    - name: Debug Environment
      run: |
        echo "CXX: $CXX"
        which g++
        g++ --version
    - name: Build mockturtle
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++-9 -DMOCKTURTLE_EXAMPLES=ON -DMOCKTURTLE_EXPERIMENTS=ON -DMOCKTURTLE_TEST=ON ..
        make
